# Generated by Django 3.2.5 on 2022-06-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='captcha_score',
        ),
    ]
