# Generated by Django 3.2.5 on 2022-06-16 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('plate_no', models.CharField(blank=True, max_length=25, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('condition', models.BooleanField(default=False)),
                ('driver_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('attendant_assigned', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('start_address', models.CharField(blank=True, max_length=70, null=True)),
                ('end_address', models.CharField(blank=True, max_length=70, null=True)),
                ('way_points', models.TextField(blank=True, max_length=300, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('distance', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(default='PickUp', max_length=50, null=True)),
                ('details', models.TextField(blank=True, max_length=500)),
                ('trip', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.route')),
            ],
        ),
    ]
