# Generated by Django 3.2.5 on 2022-06-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_buss_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss',
            name='current_address',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='way_points',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
