# Generated by Django 3.2.5 on 2022-06-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220623_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='total',
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
