# Generated by Django 3.2.5 on 2022-06-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220623_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss',
            name='status',
            field=models.CharField(default='Parking', max_length=50, null=True),
        ),
    ]
